### ISSUE TITLE
Curious about not working on Linux

### ISSUE THREAD

**Issue by lsylusiyao** [cyanfish/grpc-dotnet-namedpipes#19]
I've tried a very simple example which could easily run on Windows, but on Linux, client couldn't connect to server. I've checked the source code on git and it seems that there's no Interop about Windows API. 
I know this is targeting Windows but I'm very curious about why this package doesn't work well on Linux. Is there any suggestions about making it work on Linux? Thanks.

**Comment by cyanfish** [comment]
It might be related to this?
https://stackoverflow.com/questions/46683772/issue-with-net-core-named-pipes-on-linux-address-already-in-use

**Comment by lsylusiyao** [comment]
I've checked the source code of System.IO.Pipes. It seems that the problem you've [mentioned above](https://stackoverflow.com/questions/46683772/issue-with-net-core-named-pipes-on-linux-address-already-in-use) has [fixed](https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs#L53) so it shouldn't be the reason of not working on Linux.  

Though the absolute name of the name pipes are different between [Windows](https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Windows.cs#L21) and [Unix](https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs#L76), the server and client use the same name on one platform, so it shouldn't be the problem of name's difference. 

What's more, through the source code I've found that dotnet created a name pipe called `/tmp/CoreFx_SOMENAME`, but when I `ls` inside `/tmp`, the only thing I've got about dotnet is a list of `clr-debug-pipe-***` and `dotnet-diagnostic-***`. I'm confused about this. Thanks.

**Comment by lsylusiyao** [comment]
I find out that the true problem of not working on *nix is that, when creating the `NamedPipeServerStream`, `PipeTransmissionMode.Message` is used which is not supported on *nix ([ServerStreamPool.cs](https://github.com/cyanfish/grpc-dotnet-namedpipes/blob/master/GrpcDotNetNamedPipes/Internal/ServerStreamPool.cs#L69)). Maybe one of the reason using the `Message` is it's a quick way of [receiving data from pipe](https://github.com/cyanfish/grpc-dotnet-namedpipes/blob/master/GrpcDotNetNamedPipes/Internal/NamedPipeTransport.cs#L50).
I don't really understand how gRPC deals with message, but I find a way from a [similar project](https://github.com/jacqueskang/IpcServiceFramework/blob/e4be2cdae8f0b5d65e175f4c695aa03a2530ef5d/src/JKang.IpcServiceFramework.Core/IO/IpcReader.cs#L54) which adds some bytes in front of the stream to indicate the whole transforming bytes. This might be a way of making this project work on *nix.

**Comment by cyanfish** [comment]
Linux (and Mac) support should now work in 2.0.0.
