### ISSUE TITLE
Connection established ?

### ISSUE THREAD

**Issue by sigmarsson** [cyanfish/grpc-dotnet-namedpipes#21]
```
var channel = new NamedPipeChannel(".", "MY_PIPE_NAME");
var client = new Greeter.GreeterClient(channel);
```

Can you check if the server is listening after you execute this ?

**Comment by cyanfish** [comment]
You can set NamedPipeChannelOptions.ConnectionTimeout and then call a method on the client and it should fail within that time if the server isn't responding.

**Comment by sigmarsson** [comment]
Splendid. Do you throw ex after that period elapses or return some err?

**Comment by cyanfish** [comment]
It should throw an RpcException with StatusCode.Unavailable.
