### ISSUE TITLE
Server Stop and restart

### ISSUE THREAD

**Issue by aniljosenj** [cyanfish/grpc-dotnet-namedpipes#24]
Once we kill or dispose the server and start again we are not able to send client request, is this expected?

**Comment by cyanfish** [comment]
Yes, that's intended. I'll change it so that starting throws an exception in that case. Create a new server object to restart.

**Comment by aniljosenj** [comment]
Creating new server seems to be not working for me , 
The procedure I followed is 
1: Start server (start())
2 Kill server(tried both kill and dispose)
3: start new server object(start())
4 make client call
And the client call was unsuccessful.

**Comment by cyanfish** [comment]
Thanks for reporting! Should be fixed in https://github.com/cyanfish/grpc-dotnet-namedpipes/commit/3a70abf7f4db93f5892f6fcdfb64c40259efbeb3 and version 1.4.2 on nuget.
