### ISSUE TITLE
Strong Named

### ISSUE THREAD

**Issue by joschmo80** [cyanfish/grpc-dotnet-namedpipes#28]
Hello,

My .NET 5.0 app is strong named for security reasons.  Currently importing your nuget package shows the following warnings during build:
29>CSC : warning CS8002: Referenced assembly 'GrpcDotNetNamedPipes, Version=1.4.2.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

While the app runs despite those, would it be possible to strong name your build?  This can easily be achieved by adding the following to every .csproj:

      <AssemblyOriginatorKeyFile>..\Foo.snk</AssemblyOriginatorKeyFile>
      <SignAssembly>true</SignAssembly>

Where Foo.snk is generated per sn.exe.  See https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-use-strong-named for more info.

Thanks!

**Comment by joschmo80** [comment]
Forgot to mention, the current workaround is for my code to also add a nuget reference to https://github.com/dsplaisted/strongnamer.  This works, but is less than ideal.

**Comment by cyanfish** [comment]
Hi, I've published version 1.4.4 with strong naming.
