### ISSUE TITLE
Consider using System.IO.Pipelines

### ISSUE THREAD

**Issue by taori** [cyanfish/grpc-dotnet-namedpipes#3]
Have you considered using [System.IO.Pipelines](https://www.nuget.org/packages/System.IO.Pipelines/) to reduce allocation and increase throughput?

**Comment by cyanfish** [comment]
I haven't looked into it much. If you can find a way to use it with tangible performance benefits, I'm happy to review.

**Comment by cyanfish** [comment]
Closing this because I don't think it will have a significant impact. Happy to reopen if anyone has reason otherwise.
