### ISSUE TITLE
Server stream has not been notified when the client has been unexpectedly terminated.

### ISSUE THREAD

**Issue by ychumpov** [cyanfish/grpc-dotnet-namedpipes#30]
Here is my code:

public override async Task TestMethod(Empty request, IServerStreamWriter<TestData> responseStream, ServerCallContext context)
{
 logger.LogInfo($"request was registered!");

            // Completing the method means disconnecting the stream by server side. 
            // So just waiting the client to disconnect.
            var cts = new CancellationTokenSource();
            context.CancellationToken.Register(() =>
            {
                // This code was not called when the client has been killed.
                logger.LogInfo($"Subscription finished");
                cts.Cancel();
            });

            await AwaitCancellation(cts.Token);

}

 private static Task AwaitCancellation(CancellationToken token)
        {
            var completion = new TaskCompletionSource<object>();
            token.Register(() => completion.SetResult(null));
            return completion.Task;
        }

**Comment by cyanfish** [comment]
This should be fixed in 2.1.0.
