### ISSUE TITLE
AssemblyVersion is hard coded to 1.0.0.0 - breaks versioning with release 1.4.4

### ISSUE THREAD

**Issue by dchasman** [cyanfish/grpc-dotnet-namedpipes#36]
I've submitted a pull request with the requested fix _**Update AssemblyVersion to match PackageVersion to insure installers, … #35.**_

As a temporary workaround we have forked and built out own local nuget package with the requested change.

**Comment by cyanfish** [comment]
This should be fixed in 2.0.0.
