### ISSUE TITLE
System.NotSupportedException when reading ServerCallContext.Peer

### ISSUE THREAD

**Issue by LAB02-Admin** [cyanfish/grpc-dotnet-namedpipes#37]
I'm trying to get the `ServerCallContext.Peer` value of an incoming RPC request, but it throws an `System.NotSupportedException`. 

Is there another way to get the info of the connecting peer? The connection itself works fine.

I'm using .NET 6

**Comment by cyanfish** [comment]
This should be fixed in 2.1.0. Specifically it will return a string in the form "net.pipe://localhost/pid/12345" (where 12345 is the process id).
