### ISSUE TITLE
Document wire protocol

### ISSUE THREAD

**Issue by hellozyemlya** [cyanfish/grpc-dotnet-namedpipes#41]
It will be great if there is some documentation about wire protocol of your transport exists.

I want to try to write namedpipe transport that will be compatible with your implementation but in python.

**Comment by cyanfish** [comment]
Hi, I've done a writeup for the protocol in the [wiki](https://github.com/cyanfish/grpc-dotnet-namedpipes/wiki/Wire-Protocol), have a look and let me know if you have any questions.

**Comment by hellozyemlya** [comment]
Thanks a lot. Looks clear enough to start working with it. Will report back results later a little bit.
