### ISSUE TITLE
Why the ServerStreaming performance of gRPCPipe factory is not good as other two factorys

### ISSUE THREAD

**Issue by NeverMorewd** [cyanfish/grpc-dotnet-namedpipes#54]
![image](https://github.com/cyanfish/grpc-dotnet-namedpipes/assets/10544200/00a5180a-1278-40b9-955b-5b5b79a37f3b)

**Comment by cyanfish** [comment]
Which one is which? If the pipe one is number 3, then keep in mind lower numbers are better (less time).
